"""configure data

Revision ID: 263a45616399
Revises: 840cb804b078
Create Date: 2023-05-16 09:02:53.097562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, String, Integer, Boolean

# revision identifiers, used by Alembic.
revision = '263a45616399'
down_revision = '840cb804b078'
branch_labels = None
depends_on = None

source_groups = [
    {'name': 'PM data', 'storage': 'kpi-storage'},
    {'name': 'CM data', 'storage': None},
    {'name': 'Inventory data', 'storage': 'inventory'},
    {'name': 'Geolocated data', 'storage': None},
    {'name': 'Site finance data', 'storage': None},
    {'name': 'Network development plan', 'storage': None},
    {'name': 'Refarming plan', 'storage': None},
    {'name': 'Global finance data', 'storage': None},
    {'name': 'Cost information', 'storage': None},
    {'name': 'Competitor performance', 'storage': None},
    {'name': 'Coverage', 'storage': None}
]
has_preview = [True, True, False, True, False, False, True, False, False, True, False]
data_sources = []
for idx in range(len(source_groups)):
    data_sources.append({'name': 'default', 'group_id': idx + 1, 'has_preview': has_preview[idx]})
source_fields = [
    {'name': 'Cell Name', 'source_id': 1},
    {'name': 'Timestamp', 'source_id': 1},
    {'name': 'Utilization_DL', 'source_id': 1},
    {'name': 'UE_Throughput_DL', 'source_id': 1},
    {'name': 'Users_DL', 'source_id': 1},
    {'name': 'Traffic_DL', 'source_id': 1},

    {'name': 'Site Name', 'source_id': 2},
    {'name': 'Cell Name', 'source_id': 2},
    {'name': 'Band', 'source_id': 2},
    {'name': 'BW', 'source_id': 2},
    {'name': 'MIMO', 'source_id': 2},
    {'name': 'Vendor', 'source_id': 2},

    {'name': 'Site Name', 'source_id': 3},
    {'name': 'Latitude', 'source_id': 3},
    {'name': 'Longitude', 'source_id': 3},
    {'name': 'Region', 'source_id': 3},

    {'name': 'Timestamp', 'source_id': 4},
    {'name': 'Latitude', 'source_id': 4},
    {'name': 'Longitude', 'source_id': 4},
    {'name': 'Cell Name', 'source_id': 4},
    {'name': 'EnodeB ID', 'source_id': 4},
    {'name': 'EnodeB', 'source_id': 4},
    {'name': 'CQI', 'source_id': 4},
    {'name': 'DL Throughput', 'source_id': 4},
    {'name': 'DL Total Volume', 'source_id': 4},
    {'name': 'Subscriber Count', 'source_id': 4},

    {'name': 'Site revenues', 'source_id': 5},
    {'name': 'Site marketing scores', 'source_id': 5},

    {'name': 'Network development plan', 'source_id': 6},
    {'name': 'Refarming plan', 'source_id': 7},

    {'name': 'Forecasted traffic growth', 'source_id': 8},
    {'name': 'Target KPIs', 'source_id': 8},
    {'name': 'Average revenue per MB', 'source_id': 8},

    {'name': 'Labor costs', 'source_id': 9},
    {'name': 'Material costs', 'source_id': 9},
    {'name': 'Equipment costs', 'source_id': 9},
    {'name': 'Design costs', 'source_id': 9},
    {'name': 'Transport Cost', 'source_id': 9},
    {'name': 'Site Lease', 'source_id': 9},

    {'name': 'Competitor performance', 'source_id': 10},

    {'name': 'Coverage', 'source_id': 11}
]
previews = [
    {'name': 'Cell Name', 'value': '77-5761', 'row': 1, 'source_id': 2},
    {'name': 'Site Name', 'value': 'PL_77_5761', 'row': 1, 'source_id': 2},
    {'name': 'Band', 'value': '6', 'row': 1, 'source_id': 2},
    {'name': 'MIMO', 'value': '4x4', 'row': 1, 'source_id': 2},
    {'name': 'Vendor', 'value': 'Nokia', 'row': 1, 'source_id': 2},
    {'name': 'BW', 'value': '20.0', 'row': 1, 'source_id': 2},
    {'name': 'Cell Name', 'value': '77-603', 'row': 2, 'source_id': 2},
    {'name': 'Site Name', 'value': 'PL_77_603', 'row': 2, 'source_id': 2},
    {'name': 'Band', 'value': '6', 'row': 2, 'source_id': 2},
    {'name': 'MIMO', 'value': '4x4', 'row': 2, 'source_id': 2},
    {'name': 'Vendor', 'value': 'Nokia', 'row': 2, 'source_id': 2},
    {'name': 'BW', 'value': '20.0', 'row': 2, 'source_id': 2},
    {'name': 'Cell Name', 'value': '68-701', 'row': 3, 'source_id': 2},
    {'name': 'Site Name', 'value': 'PL_68_701', 'row': 3, 'source_id': 2},
    {'name': 'Band', 'value': '2', 'row': 3, 'source_id': 2},
    {'name': 'MIMO', 'value': '2x2', 'row': 3, 'source_id': 2},
    {'name': 'Vendor', 'value': 'Nokia', 'row': 3, 'source_id': 2},
    {'name': 'BW', 'value': '14.4', 'row': 3, 'source_id': 2},
    {'name': 'Cell Name', 'value': '31-103', 'row': 4, 'source_id': 2},
    {'name': 'Site Name', 'value': 'PL_31_103', 'row': 4, 'source_id': 2},
    {'name': 'Band', 'value': '6', 'row': 4, 'source_id': 2},
    {'name': 'MIMO', 'value': '4x4', 'row': 4, 'source_id': 2},
    {'name': 'Vendor', 'value': 'Nokia', 'row': 4, 'source_id': 2},
    {'name': 'BW', 'value': '20.0', 'row': 4, 'source_id': 2},
    {'name': 'Cell Name', 'value': '32-271', 'row': 5, 'source_id': 2},
    {'name': 'Site Name', 'value': 'PL_32_271', 'row': 5, 'source_id': 2},
    {'name': 'Band', 'value': '6', 'row': 5, 'source_id': 2},
    {'name': 'MIMO', 'value': '4x4', 'row': 5, 'source_id': 2},
    {'name': 'Vendor', 'value': 'Nokia', 'row': 5, 'source_id': 2},
    {'name': 'BW', 'value': '20.0', 'row': 5, 'source_id': 2},
    {'name': 'test_id', 'value': '4548078884', 'row': 1, 'source_id': 10},
    {'name': 'date', 'value': '2018-12-27 00:00:00', 'row': 1, 'source_id': 10},
    {'name': 'monthyear', 'value': '2018-12-01 00:00:00', 'row': 1, 'source_id': 10},
    {'name': 'downlink', 'value': '6316', 'row': 1, 'source_id': 10},
    {'name': 'ping', 'value': '29', 'row': 1, 'source_id': 10},
    {'name': 'uplink', 'value': '4704', 'row': 1, 'source_id': 10},
    {'name': 'client_latitude', 'value': '53900', 'row': 1, 'source_id': 10},
    {'name': 'client_longitude', 'value': '27566', 'row': 1, 'source_id': 10},
    {'name': 'client_country', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'client_region_name', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'client_city', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'connection_type', 'value': '3', 'row': 1, 'source_id': 10},
    {'name': 'network_type', 'value': 'GPRS', 'row': 1, 'source_id': 10},
    {'name': 'location_type', 'value': '2', 'row': 1, 'source_id': 10},
    {'name': 'network_operator_name', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'carrier_good', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'region', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'server_name', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'server_country', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'server_country_code', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'is_lte', 'value': 'no_lte', 'row': 1, 'source_id': 10},
    {'name': '2/3/4G', 'value': '2g', 'row': 1, 'source_id': 10},
    {'name': 'server_latitude', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'server_longitude', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'isp_name', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'test_date', 'value': '2018-12-27 10:03:53', 'row': 1, 'source_id': 10},
    {'name': 'gsm_cell_id', 'value': '2891', 'row': 1, 'source_id': 10},
    {'name': 'cdma_cell_id', 'value': 'nan', 'row': 1, 'source_id': 10},
    {'name': 'server_sponsor_name', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'latency', 'value': '29', 'row': 1, 'source_id': 10},
    {'name': 'mcc', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'mnc', 'value': 'X', 'row': 1, 'source_id': 10},
    {'name': 'test_id', 'value': '4521543532', 'row': 2, 'source_id': 10},
    {'name': 'date', 'value': '2018-12-17 00:00:00', 'row': 2, 'source_id': 10},
    {'name': 'monthyear', 'value': '2018-12-01 00:00:00', 'row': 2, 'source_id': 10},
    {'name': 'downlink', 'value': '3621', 'row': 2, 'source_id': 10},
    {'name': 'ping', 'value': '22', 'row': 2, 'source_id': 10},
    {'name': 'uplink', 'value': '2201', 'row': 2, 'source_id': 10},
    {'name': 'client_latitude', 'value': '53895', 'row': 2, 'source_id': 10},
    {'name': 'client_longitude', 'value': '27646', 'row': 2, 'source_id': 10},
    {'name': 'client_country', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'client_region_name', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'client_city', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'connection_type', 'value': '3', 'row': 2, 'source_id': 10},
    {'name': 'network_type', 'value': 'GPRS', 'row': 2, 'source_id': 10},
    {'name': 'location_type', 'value': '1', 'row': 2, 'source_id': 10},
    {'name': 'network_operator_name', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'carrier_good', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'region', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'server_name', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'server_country', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'server_country_code', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'is_lte', 'value': 'no_lte', 'row': 2, 'source_id': 10},
    {'name': '2/3/4G', 'value': '2g', 'row': 2, 'source_id': 10},
    {'name': 'server_latitude', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'server_longitude', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'isp_name', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'test_date', 'value': '2018-12-17 23:53:45', 'row': 2, 'source_id': 10},
    {'name': 'gsm_cell_id', 'value': '1181', 'row': 2, 'source_id': 10},
    {'name': 'cdma_cell_id', 'value': 'nan', 'row': 2, 'source_id': 10},
    {'name': 'server_sponsor_name', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'latency', 'value': '22', 'row': 2, 'source_id': 10},
    {'name': 'mcc', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'mnc', 'value': 'X', 'row': 2, 'source_id': 10},
    {'name': 'test_id', 'value': '4544531141', 'row': 3, 'source_id': 10},
    {'name': 'date', 'value': '2018-12-26 00:00:00', 'row': 3, 'source_id': 10},
    {'name': 'monthyear', 'value': '2018-12-01 00:00:00', 'row': 3, 'source_id': 10},
    {'name': 'downlink', 'value': '1883', 'row': 3, 'source_id': 10},
    {'name': 'ping', 'value': '35', 'row': 3, 'source_id': 10},
    {'name': 'uplink', 'value': '1584', 'row': 3, 'source_id': 10},
    {'name': 'client_latitude', 'value': '53896', 'row': 3, 'source_id': 10},
    {'name': 'client_longitude', 'value': '27649', 'row': 3, 'source_id': 10},
    {'name': 'client_country', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'client_region_name', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'client_city', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'connection_type', 'value': '3', 'row': 3, 'source_id': 10},
    {'name': 'network_type', 'value': 'GPRS', 'row': 3, 'source_id': 10},
    {'name': 'location_type', 'value': '1', 'row': 3, 'source_id': 10},
    {'name': 'network_operator_name', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'carrier_good', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'region', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'server_name', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'server_country', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'server_country_code', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'is_lte', 'value': 'no_lte', 'row': 3, 'source_id': 10},
    {'name': '2/3/4G', 'value': '2g', 'row': 3, 'source_id': 10},
    {'name': 'server_latitude', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'server_longitude', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'isp_name', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'test_date', 'value': '2018-12-26 07:31:33', 'row': 3, 'source_id': 10},
    {'name': 'gsm_cell_id', 'value': '1186', 'row': 3, 'source_id': 10},
    {'name': 'cdma_cell_id', 'value': 'nan', 'row': 3, 'source_id': 10},
    {'name': 'server_sponsor_name', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'latency', 'value': '35', 'row': 3, 'source_id': 10},
    {'name': 'mcc', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'mnc', 'value': 'X', 'row': 3, 'source_id': 10},
    {'name': 'test_id', 'value': '4502041726', 'row': 4, 'source_id': 10},
    {'name': 'date', 'value': '2018-12-10 00:00:00', 'row': 4, 'source_id': 10},
    {'name': 'monthyear', 'value': '2018-12-01 00:00:00', 'row': 4, 'source_id': 10},
    {'name': 'downlink', 'value': '6985', 'row': 4, 'source_id': 10},
    {'name': 'ping', 'value': '21', 'row': 4, 'source_id': 10},
    {'name': 'uplink', 'value': '2363', 'row': 4, 'source_id': 10},
    {'name': 'client_latitude', 'value': '53896', 'row': 4, 'source_id': 10},
    {'name': 'client_longitude', 'value': '27649', 'row': 4, 'source_id': 10},
    {'name': 'client_country', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'client_region_name', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'client_city', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'connection_type', 'value': '3', 'row': 4, 'source_id': 10},
    {'name': 'network_type', 'value': 'GPRS', 'row': 4, 'source_id': 10},
    {'name': 'location_type', 'value': '1', 'row': 4, 'source_id': 10},
    {'name': 'network_operator_name', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'carrier_good', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'region', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'server_name', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'server_country', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'server_country_code', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'is_lte', 'value': 'no_lte', 'row': 4, 'source_id': 10},
    {'name': '2/3/4G', 'value': '2g', 'row': 4, 'source_id': 10},
    {'name': 'server_latitude', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'server_longitude', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'isp_name', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'test_date', 'value': '2018-12-10 22:15:18', 'row': 4, 'source_id': 10},
    {'name': 'gsm_cell_id', 'value': '4522', 'row': 4, 'source_id': 10},
    {'name': 'cdma_cell_id', 'value': 'nan', 'row': 4, 'source_id': 10},
    {'name': 'server_sponsor_name', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'latency', 'value': '21', 'row': 4, 'source_id': 10},
    {'name': 'mcc', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'mnc', 'value': 'X', 'row': 4, 'source_id': 10},
    {'name': 'test_id', 'value': '4556902970', 'row': 5, 'source_id': 10},
    {'name': 'date', 'value': '2018-12-30 00:00:00', 'row': 5, 'source_id': 10},
    {'name': 'monthyear', 'value': '2018-12-01 00:00:00', 'row': 5, 'source_id': 10},
    {'name': 'downlink', 'value': '1402', 'row': 5, 'source_id': 10},
    {'name': 'ping', 'value': '39', 'row': 5, 'source_id': 10},
    {'name': 'uplink', 'value': '2305', 'row': 5, 'source_id': 10},
    {'name': 'client_latitude', 'value': '54227', 'row': 5, 'source_id': 10},
    {'name': 'client_longitude', 'value': '28505', 'row': 5, 'source_id': 10},
    {'name': 'client_country', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'client_region_name', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'client_city', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'connection_type', 'value': '3', 'row': 5, 'source_id': 10},
    {'name': 'network_type', 'value': 'GPRS', 'row': 5, 'source_id': 10},
    {'name': 'location_type', 'value': '2', 'row': 5, 'source_id': 10},
    {'name': 'network_operator_name', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'carrier_good', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'region', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'server_name', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'server_country', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'server_country_code', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'is_lte', 'value': 'no_lte', 'row': 5, 'source_id': 10},
    {'name': '2/3/4G', 'value': '2g', 'row': 5, 'source_id': 10},
    {'name': 'server_latitude', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'server_longitude', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'isp_name', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'test_date', 'value': '2018-12-30 10:54:23', 'row': 5, 'source_id': 10},
    {'name': 'gsm_cell_id', 'value': '8646', 'row': 5, 'source_id': 10},
    {'name': 'cdma_cell_id', 'value': 'nan', 'row': 5, 'source_id': 10},
    {'name': 'server_sponsor_name', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'latency', 'value': '39', 'row': 5, 'source_id': 10},
    {'name': 'mcc', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'mnc', 'value': 'X', 'row': 5, 'source_id': 10},
    {'name': 'cell_name', 'value': '1007022', 'row': 1, 'source_id': 4},
    {'name': 'gnodeb_id', 'value': '100702', 'row': 1, 'source_id': 4},
    {'name': 'timestamp', 'value': '2022-12-31 00:00:00', 'row': 1, 'source_id': 4},
    {'name': 'latitude', 'value': '40.50939190128882', 'row': 1, 'source_id': 4},
    {'name': 'longitude', 'value': '-74.24700390547513', 'row': 1, 'source_id': 4},
    {'name': 'cqi_count', 'value': '2', 'row': 1, 'source_id': 4},
    {'name': 'cqi_sum', 'value': '8', 'row': 1, 'source_id': 4},
    {'name': 'dl_total_volume', 'value': '171850000.0', 'row': 1, 'source_id': 4},
    {'name': 'dl_duration_ms', 'value': '149102.069', 'row': 1, 'source_id': 4},
    {'name': 'subscriber_count', 'value': '5.0', 'row': 1, 'source_id': 4},
    {'name': 'cell_name', 'value': '1007031', 'row': 2, 'source_id': 4},
    {'name': 'gnodeb_id', 'value': '100703', 'row': 2, 'source_id': 4},
    {'name': 'timestamp', 'value': '2022-12-31 00:00:00', 'row': 2, 'source_id': 4},
    {'name': 'latitude', 'value': '40.51744734671337', 'row': 2, 'source_id': 4},
    {'name': 'longitude', 'value': '-74.24081906676292', 'row': 2, 'source_id': 4},
    {'name': 'cqi_count', 'value': '10', 'row': 2, 'source_id': 4},
    {'name': 'cqi_sum', 'value': '44', 'row': 2, 'source_id': 4},
    {'name': 'dl_total_volume', 'value': '310549300.0', 'row': 2, 'source_id': 4},
    {'name': 'dl_duration_ms', 'value': '878755.85', 'row': 2, 'source_id': 4},
    {'name': 'subscriber_count', 'value': '4.0', 'row': 2, 'source_id': 4},
    {'name': 'cell_name', 'value': '1007046', 'row': 3, 'source_id': 4},
    {'name': 'gnodeb_id', 'value': '100704', 'row': 3, 'source_id': 4},
    {'name': 'timestamp', 'value': '2022-12-31 00:00:00', 'row': 3, 'source_id': 4},
    {'name': 'latitude', 'value': '40.51310813515647', 'row': 3, 'source_id': 4},
    {'name': 'longitude', 'value': '-74.22163724899292', 'row': 3, 'source_id': 4},
    {'name': 'cqi_count', 'value': '4', 'row': 3, 'source_id': 4},
    {'name': 'cqi_sum', 'value': '24', 'row': 3, 'source_id': 4},
    {'name': 'dl_total_volume', 'value': '196342900.0', 'row': 3, 'source_id': 4},
    {'name': 'dl_duration_ms', 'value': '115770.932', 'row': 3, 'source_id': 4},
    {'name': 'subscriber_count', 'value': '11.0', 'row': 3, 'source_id': 4},
    {'name': 'cell_name', 'value': '1007049', 'row': 4, 'source_id': 4},
    {'name': 'gnodeb_id', 'value': '100704', 'row': 4, 'source_id': 4},
    {'name': 'timestamp', 'value': '2022-12-31 00:00:00', 'row': 4, 'source_id': 4},
    {'name': 'latitude', 'value': '40.52222754408855', 'row': 4, 'source_id': 4},
    {'name': 'longitude', 'value': '-74.23454638805362', 'row': 4, 'source_id': 4},
    {'name': 'cqi_count', 'value': '2', 'row': 4, 'source_id': 4},
    {'name': 'cqi_sum', 'value': '7', 'row': 4, 'source_id': 4},
    {'name': 'dl_total_volume', 'value': '163743800.0', 'row': 4, 'source_id': 4},
    {'name': 'dl_duration_ms', 'value': '107637.799', 'row': 4, 'source_id': 4},
    {'name': 'subscriber_count', 'value': '1.0', 'row': 4, 'source_id': 4},
    {'name': 'cell_name', 'value': '1007056', 'row': 5, 'source_id': 4},
    {'name': 'gnodeb_id', 'value': '100705', 'row': 5, 'source_id': 4},
    {'name': 'timestamp', 'value': '2022-12-31 00:00:00', 'row': 5, 'source_id': 4},
    {'name': 'latitude', 'value': '40.5173864304496', 'row': 5, 'source_id': 4},
    {'name': 'longitude', 'value': '-74.19633965939283', 'row': 5, 'source_id': 4},
    {'name': 'cqi_count', 'value': '4', 'row': 5, 'source_id': 4},
    {'name': 'cqi_sum', 'value': '33', 'row': 5, 'source_id': 4},
    {'name': 'dl_total_volume', 'value': '172971400.0', 'row': 5, 'source_id': 4},
    {'name': 'dl_duration_ms', 'value': '372107.22', 'row': 5, 'source_id': 4},
    {'name': 'subscriber_count', 'value': '2.0', 'row': 5, 'source_id': 4},
    {'name': 'Cell Name', 'value': '1007022', 'row': 1, 'source_id': 1},
    {'name': 'Utilization_DL_N', 'value': '426723200000.0', 'row': 1, 'source_id': 1},
    {'name': 'Utilization_DL_DN', 'value': '8640000000.0', 'row': 1, 'source_id': 1},
    {'name': 'Traffic_DL', 'value': '171850000.0', 'row': 1, 'source_id': 1},
    {'name': 'UE_Throughput_DL_N', 'value': '1227840000.0', 'row': 1, 'source_id': 1},
    {'name': 'UE_Throughput_DL_DN', 'value': '149102.069', 'row': 1, 'source_id': 1},
    {'name': 'Users_DL', 'value': '92.0', 'row': 1, 'source_id': 1},
    {'name': 'Timestamp', 'value': '2022-12-31 00:00:00', 'row': 1, 'source_id': 1},
    {'name': 'Cell Name', 'value': '1007031', 'row': 2, 'source_id': 1},
    {'name': 'Utilization_DL_N', 'value': '743798500000.0', 'row': 2, 'source_id': 1},
    {'name': 'Utilization_DL_DN', 'value': '8640000000.0', 'row': 2, 'source_id': 1},
    {'name': 'Traffic_DL', 'value': '310549300.0', 'row': 2, 'source_id': 1},
    {'name': 'UE_Throughput_DL_N', 'value': '2244760000.0', 'row': 2, 'source_id': 1},
    {'name': 'UE_Throughput_DL_DN', 'value': '878755.85', 'row': 2, 'source_id': 1},
    {'name': 'Users_DL', 'value': '146.0', 'row': 2, 'source_id': 1},
    {'name': 'Timestamp', 'value': '2022-12-31 00:00:00', 'row': 2, 'source_id': 1},
    {'name': 'Cell Name', 'value': '1007046', 'row': 3, 'source_id': 1},
    {'name': 'Utilization_DL_N', 'value': '472905500000.0', 'row': 3, 'source_id': 1},
    {'name': 'Utilization_DL_DN', 'value': '8640000000.0', 'row': 3, 'source_id': 1},
    {'name': 'Traffic_DL', 'value': '196342900.0', 'row': 3, 'source_id': 1},
    {'name': 'UE_Throughput_DL_N', 'value': '1355159000.0', 'row': 3, 'source_id': 1},
    {'name': 'UE_Throughput_DL_DN', 'value': '115770.932', 'row': 3, 'source_id': 1},
    {'name': 'Users_DL', 'value': '126.0', 'row': 3, 'source_id': 1},
    {'name': 'Timestamp', 'value': '2022-12-31 00:00:00', 'row': 3, 'source_id': 1},
    {'name': 'Cell Name', 'value': '1007049', 'row': 4, 'source_id': 1},
    {'name': 'Utilization_DL_N', 'value': '375477100000.0', 'row': 4, 'source_id': 1},
    {'name': 'Utilization_DL_DN', 'value': '6480000000.0', 'row': 4, 'source_id': 1},
    {'name': 'Traffic_DL', 'value': '163743800.0', 'row': 4, 'source_id': 1},
    {'name': 'UE_Throughput_DL_N', 'value': '1164647000.0', 'row': 4, 'source_id': 1},
    {'name': 'UE_Throughput_DL_DN', 'value': '107637.799', 'row': 4, 'source_id': 1},
    {'name': 'Users_DL', 'value': '106.0', 'row': 4, 'source_id': 1},
    {'name': 'Timestamp', 'value': '2022-12-31 00:00:00', 'row': 4, 'source_id': 1},
    {'name': 'Cell Name', 'value': '1007056', 'row': 5, 'source_id': 1},
    {'name': 'Utilization_DL_N', 'value': '450344200000.0', 'row': 5, 'source_id': 1},
    {'name': 'Utilization_DL_DN', 'value': '8640000000.0', 'row': 5, 'source_id': 1},
    {'name': 'Traffic_DL', 'value': '172971400.0', 'row': 5, 'source_id': 1},
    {'name': 'UE_Throughput_DL_N', 'value': '1269195000.0', 'row': 5, 'source_id': 1},
    {'name': 'UE_Throughput_DL_DN', 'value': '372107.22', 'row': 5, 'source_id': 1},
    {'name': 'Users_DL', 'value': '190.0', 'row': 5, 'source_id': 1},
    {'name': 'Timestamp', 'value': '2022-12-31 00:00:00', 'row': 5, 'source_id': 1},
    {'name': 'Cluster', 'value': 'Flushing', 'row': 1, 'source_id': 7},
    {'name': 'Band', 'value': '6', 'row': 1, 'source_id': 7},
    {'name': 'BW1', 'value': '10', 'row': 1, 'source_id': 7},
    {'name': 'BW2', 'value': '15', 'row': 1, 'source_id': 7},
    {'name': 'Date', 'value': '01.02.2023', 'row': 1, 'source_id': 7},
    {'name': 'Cluster', 'value': 'Richmond Hill', 'row': 2, 'source_id': 7},
    {'name': 'Band', 'value': '6', 'row': 2, 'source_id': 7},
    {'name': 'BW1', 'value': '10', 'row': 2, 'source_id': 7},
    {'name': 'BW2', 'value': '15', 'row': 2, 'source_id': 7},
    {'name': 'Date', 'value': '01.02.2023', 'row': 2, 'source_id': 7},
    {'name': 'Cluster', 'value': 'Midwood', 'row': 3, 'source_id': 7},
    {'name': 'Band', 'value': '6', 'row': 3, 'source_id': 7},
    {'name': 'BW1', 'value': '10', 'row': 3, 'source_id': 7},
    {'name': 'BW2', 'value': '15', 'row': 3, 'source_id': 7},
    {'name': 'Date', 'value': '01.02.2023', 'row': 3, 'source_id': 7},
    {'name': 'Cluster', 'value': 'Canarsie', 'row': 4, 'source_id': 7},
    {'name': 'Band', 'value': '6', 'row': 4, 'source_id': 7},
    {'name': 'BW1', 'value': '10', 'row': 4, 'source_id': 7},
    {'name': 'BW2', 'value': '15', 'row': 4, 'source_id': 7},
    {'name': 'Date', 'value': '01.02.2023', 'row': 4, 'source_id': 7},
    {'name': 'Cluster', 'value': 'Sheepshead Bay', 'row': 5, 'source_id': 7},
    {'name': 'Band', 'value': '6', 'row': 5, 'source_id': 7},
    {'name': 'BW1', 'value': '10', 'row': 5, 'source_id': 7},
    {'name': 'BW2', 'value': '15', 'row': 5, 'source_id': 7},
    {'name': 'Date', 'value': '01.02.2023', 'row': 5, 'source_id': 7},
]


def upgrade() -> None:
    # SourceGroup
    source_groups_table = table('source_groups',
                                column('name', String),
                                column('storage', String))
    op.bulk_insert(source_groups_table, source_groups)

    # DataSource
    data_sources_table = table('data_sources',
                               column('name', String),
                               column('group_id', Integer),
                               column('has_preview', Boolean))
    op.bulk_insert(data_sources_table, data_sources)

    # SourceField
    source_fields_table = table('source_fields',
                                column('name', String),
                                column('source_id', Integer))
    op.bulk_insert(source_fields_table, source_fields)

    # Previews
    previews_table = table('previews',
                           column('name', String),
                           column('value', String),
                           column('row', Integer),
                           column('source_id', Integer))
    op.bulk_insert(previews_table, previews)


def downgrade() -> None:
    op.execute(sa.text("""TRUNCATE TABLE previews CASCADE"""))
    op.execute(sa.text("""TRUNCATE TABLE source_fields CASCADE"""))
    op.execute(sa.text("""TRUNCATE TABLE data_sources CASCADE"""))
    op.execute(sa.text("""TRUNCATE TABLE source_groups CASCADE"""))
