"""added file settings

Revision ID: 4ea633b2ab1e
Revises: c8a753f9f780
Create Date: 2023-06-07 17:27:29.131355

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4ea633b2ab1e'
down_revision = 'c8a753f9f780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('operation_id', sa.Integer(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=False),
                    sa.Column('extension', sa.String(length=8), nullable=False),
                    sa.CheckConstraint("extension = 'csv' OR extension = 'xlsx' OR extension = 'json'",
                                       name='file_settings_extension_check'),
                    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name='file_settings_operation_fkey'),
                    sa.PrimaryKeyConstraint('id', name='file_settings_pkey'),
                    sa.UniqueConstraint('operation_id', name='file_settings_operation_uc')
                    )
    op.create_table('sftp_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('operation_id', sa.Integer(), nullable=False),
                    sa.Column('host', sa.String(length=32), nullable=False),
                    sa.Column('port', sa.String(length=4), nullable=False),
                    sa.Column('user', sa.String(length=128), nullable=True),
                    sa.Column('password', sa.String(length=128), nullable=True),
                    sa.Column('file_path', sa.String(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name='sftp_settings_operation_fkey'),
                    sa.PrimaryKeyConstraint('id', name='sftp_settings_pkey'),
                    sa.UniqueConstraint('operation_id', name='sftp_settings_operation_uc')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sftp_settings')
    op.drop_table('file_settings')
    # ### end Alembic commands ###
