"""auth_settings_changed

Revision ID: 5a3f657fb352
Revises: f513e2c9d061
Create Date: 2023-06-09 12:15:48.300230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3f657fb352'
down_revision = 'f513e2c9d061'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key('api_auth_settings_fkey', 'api_auth', 'api_settings', ['settings_id'], ['id'])
    op.drop_column('api_auth', 'auth_type')
    op.drop_constraint('api_settings_auth_fkey', 'api_settings', type_='foreignkey')
    op.drop_column('api_settings', 'auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_settings', sa.Column('auth', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('api_settings_auth_fkey', 'api_settings', 'api_auth', ['auth'], ['id'])
    op.add_column('api_auth', sa.Column('auth_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint('api_auth_settings_fkey', 'api_auth', type_='foreignkey')
    op.drop_column('api_auth', 'settings_id')
    # ### end Alembic commands ###
