"""create models

Revision ID: 840cb804b078
Revises: 8c32b84695b9
Create Date: 2023-05-16 09:00:32.873196

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '840cb804b078'
down_revision = '8c32b84695b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_groups',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.Column('storage', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id', name='source_groups_pkey'),
                    sa.UniqueConstraint('name', name='source_groups_name_uc')
                    )
    op.create_table('data_sources',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.Column('has_preview', sa.Boolean(), server_default='False', nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['source_groups.id'], name='data_sources_group_fkey'),
                    sa.PrimaryKeyConstraint('id', name='data_sources_pkey'),
                    sa.UniqueConstraint('name', 'group_id', name='data_sources_name_uc')
                    )
    op.create_table('previews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=True),
                    sa.Column('value', sa.String(length=32), nullable=True),
                    sa.Column('row', sa.Integer(), nullable=True),
                    sa.Column('source_id', sa.Integer(), nullable=True),
                    sa.CheckConstraint('row BETWEEN 1 AND 5', name='previews_row_check'),
                    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name='previews_source_fkey'),
                    sa.PrimaryKeyConstraint('id', name='previews_pkey')
                    )
    op.create_table('source_fields',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('source_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name='source_fields_source_fkey'),
                    sa.PrimaryKeyConstraint('id', name='source_fields_pkey'),
                    sa.UniqueConstraint('name', 'source_id', name='source_fields_name_uc')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_fields')
    op.drop_table('previews')
    op.drop_table('data_sources')
    op.drop_table('source_groups')
    # ### end Alembic commands ###
