"""added api settings

Revision ID: bded6d850ee8
Revises: 4ea633b2ab1e
Create Date: 2023-06-07 19:05:53.575381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bded6d850ee8'
down_revision = '4ea633b2ab1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('secret', sa.String(length=128), nullable=True),
    sa.CheckConstraint("auth_type = 'basic' OR auth_type = 'token' OR auth_type = 'sso'", name='api_auth_type_check'),
    sa.PrimaryKeyConstraint('id', name='api_auth_pkey')
    )
    op.create_table('api_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('entry_point', sa.String(length=32), nullable=False),
    sa.Column('end_point', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('auth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth'], ['api_auth.id'], name='api_settings_auth_fkey'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name='api_settings_operation_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_settings_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_settings')
    op.drop_table('api_auth')
    # ### end Alembic commands ###
