"""added dag settings

Revision ID: c8a753f9f780
Revises: 263a45616399
Create Date: 2023-06-07 17:09:03.600416

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8a753f9f780'
down_revision = '263a45616399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source_id', sa.Integer(), nullable=False),
                    sa.Column('operation_type', sa.String(length=16), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.CheckConstraint("operation_type = 'extract'\n"
                                       "OR operation_type = 'transform'\n"
                                       "OR operation_type = 'load'", name='operations_type_check'),
                    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name='operations_source_fkey'),
                    sa.PrimaryKeyConstraint('id', name='operations_pkey'),
                    sa.UniqueConstraint('source_id', 'name', name='operations_uc')
                    )
    op.create_table('db_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('operation_id', sa.Integer(), nullable=False),
                    sa.Column('driver', sa.String(length=16), nullable=False),
                    sa.Column('host', sa.String(length=32), nullable=False),
                    sa.Column('port', sa.String(length=4), nullable=False),
                    sa.Column('user', sa.String(length=128), nullable=True),
                    sa.Column('password', sa.String(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name='db_settings_operation_fkey'),
                    sa.PrimaryKeyConstraint('id', name='db_settings_pkey'),
                    sa.UniqueConstraint('operation_id', name='db_settings_operation_uc')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_settings')
    op.drop_table('operations')
    # ### end Alembic commands ###
