"""table in db settings

Revision ID: f513e2c9d061
Revises: bded6d850ee8
Create Date: 2023-06-08 19:26:36.742615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f513e2c9d061'
down_revision = 'bded6d850ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_settings', sa.Column('table', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_settings', 'table')
    # ### end Alembic commands ###
