name: avataa-platform

# x-logging: &logging
#   logging:
#     driver: loki
#     options:
#       loki-url: http://loki:3100/loki/api/v1/push
#       loki-external-labels: job=dockerlogs,owner=avataa,environment=${PLATFORM_PROJECT_ENVIRONMENT:?}

x-logging: &logging
  logging:
    options:
      max-size: 100m

x-networks: &networks
  networks:
    - avataa-platform

x-restart: &restart
  restart: always

networks:
  avataa-platform:
    external: true

services:

  dataflow:
    <<: [*logging, *networks, *restart]
    image: ${REGISTRY_URL:?}/${PLATFORM_PROJECT_NAME:?}/ms/dataflow:${DATAFLOW_VERSION:?}
    container_name: dataflow
    ports:
      - "8000:8000"
    expose:
      - "8000"
      - "50051"
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/8000 && :> /dev/tcp/127.0.0.1/50051 || exit 1'"]
      interval: 3s
      timeout: 1s
      retries: 10
    hostname: dataflow
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 6000M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 50M

  dataflow-healthcheck:
    <<: *networks
    image: ${REGISTRY_URL:?}/${PLATFORM_PROJECT_NAME:?}/curl:${HEALTHCHECK_VERSION:?}
    container_name: dataflow-healthcheck
    depends_on:
      dataflow:
        condition: service_healthy


