# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dag_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61g_manager.proto\x12\x0b\x64\x61g_manager\"\'\n\x14RequestSourceConData\x12\x0f\n\x07sources\x18\x01 \x03(\x05\"\x8a\x01\n\x15ResponseSourceConData\x12\x41\n\x08\x63on_data\x18\x01 \x03(\x0b\x32/.dag_manager.ResponseSourceConData.ConDataEntry\x1a.\n\x0c\x43onDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\x17RequestCheckDestination\x12\x16\n\x0e\x64\x65stination_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63on_type\x18\x02 \x01(\t\"\x1a\n\x18ResponseCheckDestination2\xcc\x01\n\nDagManager\x12[\n\x10GetSourceConData\x12!.dag_manager.RequestSourceConData\x1a\".dag_manager.ResponseSourceConData\"\x00\x12\x61\n\x10\x43heckDestination\x12$.dag_manager.RequestCheckDestination\x1a%.dag_manager.ResponseCheckDestination\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dag_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSESOURCECONDATA_CONDATAENTRY._options = None
  _RESPONSESOURCECONDATA_CONDATAENTRY._serialized_options = b'8\001'
  _REQUESTSOURCECONDATA._serialized_start=34
  _REQUESTSOURCECONDATA._serialized_end=73
  _RESPONSESOURCECONDATA._serialized_start=76
  _RESPONSESOURCECONDATA._serialized_end=214
  _RESPONSESOURCECONDATA_CONDATAENTRY._serialized_start=168
  _RESPONSESOURCECONDATA_CONDATAENTRY._serialized_end=214
  _REQUESTCHECKDESTINATION._serialized_start=216
  _REQUESTCHECKDESTINATION._serialized_end=283
  _RESPONSECHECKDESTINATION._serialized_start=285
  _RESPONSECHECKDESTINATION._serialized_end=311
  _DAGMANAGER._serialized_start=314
  _DAGMANAGER._serialized_end=518
# @@protoc_insertion_point(module_scope)
