# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dag_manager_pb2 as dag__manager__pb2


class DagManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSourceConData = channel.unary_unary(
                '/dag_manager.DagManager/GetSourceConData',
                request_serializer=dag__manager__pb2.RequestSourceConData.SerializeToString,
                response_deserializer=dag__manager__pb2.ResponseSourceConData.FromString,
                )
        self.CheckDestination = channel.unary_unary(
                '/dag_manager.DagManager/CheckDestination',
                request_serializer=dag__manager__pb2.RequestCheckDestination.SerializeToString,
                response_deserializer=dag__manager__pb2.ResponseCheckDestination.FromString,
                )


class DagManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSourceConData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDestination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DagManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSourceConData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceConData,
                    request_deserializer=dag__manager__pb2.RequestSourceConData.FromString,
                    response_serializer=dag__manager__pb2.ResponseSourceConData.SerializeToString,
            ),
            'CheckDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDestination,
                    request_deserializer=dag__manager__pb2.RequestCheckDestination.FromString,
                    response_serializer=dag__manager__pb2.ResponseCheckDestination.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dag_manager.DagManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DagManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSourceConData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dag_manager.DagManager/GetSourceConData',
            dag__manager__pb2.RequestSourceConData.SerializeToString,
            dag__manager__pb2.ResponseSourceConData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dag_manager.DagManager/CheckDestination',
            dag__manager__pb2.RequestCheckDestination.SerializeToString,
            dag__manager__pb2.ResponseCheckDestination.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
