"""destinations

Revision ID: 3e14c294b854
Revises: 646440871cbc
Create Date: 2024-07-04 17:23:22.655612

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3e14c294b854'
down_revision = '646440871cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.Column('con_type', sa.String(length=32), nullable=False),
                    sa.Column('con_data', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='destinations_pkey'),
                    sa.UniqueConstraint('name', name='destinations_name_uc')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    # ### end Alembic commands ###
