"""cascade source deletion

Revision ID: 646440871cbc
Revises: c54452495422
Create Date: 2024-06-06 16:08:24.443683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646440871cbc'
down_revision = 'c54452495422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sources_group_id_fkey', 'sources', type_='foreignkey')
    op.create_foreign_key('sources_group_id_fkey', 'sources', 'source_groups', ['group_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sources_group_id_fkey', 'sources', type_='foreignkey')
    op.create_foreign_key('sources_group_id_fkey', 'sources', 'source_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
