"""initial

Revision ID: c54452495422
Revises: 
Create Date: 2024-06-06 15:51:27.497911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import Inspector

# revision identifiers, used by Alembic.
revision = 'c54452495422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = Inspector(op.get_bind())
    if not inspector.has_table('source_groups'):
        op.create_table('source_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('source_type', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='source_groups_name_uc')
        )

    if not inspector.has_table('sources'):
        op.create_table('sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('con_type', sa.String(length=32), nullable=False),
        sa.Column('con_data', sa.Text(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['source_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('group_id', 'name', name='sources_name_group_id_uc')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = Inspector(op.get_bind())
    if inspector.has_table('sources'):
        op.drop_table('sources')
    if inspector.has_table('source_groups'):
        op.drop_table('source_groups')
    # ### end Alembic commands ###
