import os

INVENTORY_HOST = os.environ.get("INVENTORY_HOST", "inventory")
INVENTORY_GRPC_PORT = os.environ.get("INVENTORY_GRPC_PORT", "50051")
INVENTORY_GRPC_URL = f"{INVENTORY_HOST}:{INVENTORY_GRPC_PORT}"
