# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import airflow_to_dataflow_pb2 as airflow__to__dataflow__pb2


class AirflowToDataflowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSourceConfiguration = channel.unary_unary(
                '/airflow_to_dataflow.AirflowToDataflow/GetSourceConfiguration',
                request_serializer=airflow__to__dataflow__pb2.RequestGetSourceConfiguration.SerializeToString,
                response_deserializer=airflow__to__dataflow__pb2.ResponseGetSourceConfiguration.FromString,
                )
        self.GetDestinationData = channel.unary_unary(
                '/airflow_to_dataflow.AirflowToDataflow/GetDestinationData',
                request_serializer=airflow__to__dataflow__pb2.RequestGetDestinationData.SerializeToString,
                response_deserializer=airflow__to__dataflow__pb2.ResponseGetDestinationData.FromString,
                )


class AirflowToDataflowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSourceConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDestinationData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirflowToDataflowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSourceConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceConfiguration,
                    request_deserializer=airflow__to__dataflow__pb2.RequestGetSourceConfiguration.FromString,
                    response_serializer=airflow__to__dataflow__pb2.ResponseGetSourceConfiguration.SerializeToString,
            ),
            'GetDestinationData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDestinationData,
                    request_deserializer=airflow__to__dataflow__pb2.RequestGetDestinationData.FromString,
                    response_serializer=airflow__to__dataflow__pb2.ResponseGetDestinationData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'airflow_to_dataflow.AirflowToDataflow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AirflowToDataflow(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSourceConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/airflow_to_dataflow.AirflowToDataflow/GetSourceConfiguration',
            airflow__to__dataflow__pb2.RequestGetSourceConfiguration.SerializeToString,
            airflow__to__dataflow__pb2.ResponseGetSourceConfiguration.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDestinationData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/airflow_to_dataflow.AirflowToDataflow/GetDestinationData',
            airflow__to__dataflow__pb2.RequestGetDestinationData.SerializeToString,
            airflow__to__dataflow__pb2.ResponseGetDestinationData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
